services:
  api-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echocad_api
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  ollama-model-puller:
    image: curlimages/curl:latest
    container_name: ollama_puller
    depends_on:
      - ollama
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "until curl -s http://ollama:11434/api/tags > /dev/null; do
        echo 'Aguardando Ollama iniciar...'
        sleep 5
      done
      echo 'Baixando modelo qwen2.5:8b...'
      curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"qwen2.5:8b\"}'"

volumes:
  ollama_data: